### ISSUE TITLE
pr-str instead of str for additional args?

### ISSUE THREAD

**Issue by mikesperber** [ptaoussanis/timbre#133]
We frequently have objects we want to include in log messages that are records, lazy seqs etc.

Timbre doesn't print those very well, as it essentially passes them all to `str`. Wouldn't `pr-str` be better?  (I.e. `(enc/spaced-str (map pr-str vargs))`in `log1-fn`.)

**Comment by ptaoussanis** [comment]
Hi Mike, 

Hmm- I'm a little conflicted about this. It's a very reasonable suggestion, esp. since things like records don't currently print useful info with `str`.

Semantically, I feel like `pr-str` should generally be preferred only for stuff that's intended for later re-reading. And it'll often include info we don't want, to support the re-reading. `str` should theoretically be what we want here. For example, I kind of like the default behaviour being to not realise lazy seqs (which might trigger unintended effects, etc.).

But that argument doesn't hold up against records... not sure what the rationale was for not making record strings more useful.

Hmm- besides records and lazy seqs, is there anything else you're finding `str` is dropping important info on? We could potentially just do a `record?` check for that one case instead of switching to `pr-str`.

As an alternative / temporary workaround, please also note that appenders receive a `:vargs_` key which contains all raw logging arguments (i.e. before any string processing, etc.)- you could always grab the raw args when you like.

Thanks again for bringing this up, will also give it some more thought from my end- just have my hands very full atm so needing to juggle some things.

**Comment by mikesperber** [comment]
Thanks for the elaborate reply!

(Indeed, that's the workaround I employed.)

Printing records properly would get me 80% of the way, lazy seqs probably another 19%.

The issue with lazy seqs is that I'd like to avoid realizing them if logging does not happen, but I take your point.

**Comment by ptaoussanis** [comment]
No problem. Okay, let me think about this for a bit. Have something in mind that might be worth trying.

**Comment by ptaoussanis** [comment]
Hi Mike,

Just pushed `[com.taoensso/timbre "4.2.0-SNAPSHOT"]` to Clojars which'll use `pr-str` for records when using Clojure 1.7+. 

Lazy seqs will be treated as before (i.e. no auto realization) since I think that's probably the safer default behaviour. Needing to manually realise lazy seqs is only irritating where auto-realising may actually be dangerous.

Thanks again for your input on this.

**Comment by mikesperber** [comment]
Many thanks!

**Comment by bostonaholic** [comment]
Due to this update, my logs are now littered with `nil`

```

**Comment by ptaoussanis** [comment]
Hi Matthew,

Yes - this was an intentional change. Previously, nil arguments wouldn't show up for print-style logging calls (`info`, `debug`, etc.). That's the usual behaviour for `print`, `str` and co. - but something that I think's suboptimal for logging where you usually want to know if a particular argument is present but nil.

So chose to adopt the convention that `nil` vals now get represented by the `"nil"` string similar to how string formatting would show a `nil` as `"null"`.

If you're seeing `nil`s in your logging output, that means you're providing logging arguments whose values are `nil`. Those were previously hidden, they're now being displayed.

Does that make sense?

**Comment by bostonaholic** [comment]
That makes sense. Now I just have to figure out what I'm passing as `nil`.

**Comment by ptaoussanis** [comment]
Just FYI - for the particular example you posted above - looks like it'd be whatever the first arg is that you're providing to that `info` call.
