### ISSUE TITLE
Exception in thread “main” Could not locate taoensso/timbre/appenders/rotor__init.class

### ISSUE THREAD

**Issue by vendethiel** [ptaoussanis/timbre#136]
Hi,

Trying to upgrade timbre from `3.4.0` to `4.1.4`, I'm getting this error:

```
Exception in thread “main” java.io.FileNotFoundException: Could not locate taoensso/timbre/appenders/rotor__init.class or taoensso/timbre/appenders/rotor.clj on classpath., compiling: $FILE

..
Caused by: java.io.FileNotFoundException: Could not locate taoensso/timbre/appenders/rotor__init.class or taoensso/timbre/appenders/rotor.clj on classpath.
```

it seems I'm not the only one as well, since I found an article about it on medium: https://medium.com/@sagarjauhari/hello-clojure-2619786bdb9a

**Comment by ptaoussanis** [comment]
Hi there,

Sounds like you might need to update your appender namespace forms for Timbre v4 - please see the **Migration checklist** at https://github.com/ptaoussanis/timbre/releases/tag/v4.0.0

Does that help?

**Comment by vendethiel** [comment]
Oh, so it's just me not used enough to clojure errors? Sorry. I thought something else was going on because of that empty classpath, but it seems I just wasted some of your time. I'll follow this list, thank you.

**Comment by ptaoussanis** [comment]
No problem :-)

The 3rd party appender namespaces changed from Timbre v3 to v4, so you're trying to import a namespace (with the old name) which no longer exists.

That's triggering the `java.io.FileNotFoundException` exception since the Clojure compiler will check for files specified for each of your namespace imports.

This is an easy error to trip on and it's my fault for changing the namespaces between v3 and v4 :-)

Does that make sense?

**Comment by vendethiel** [comment]
Yes, definitely ! I'm just not enough of a clojurian to recognize this error :-). Thanks

**Comment by vendethiel** [comment]
all's well in the world! thanks again.

**Comment by ptaoussanis** [comment]
No problem, and good luck with the Clojure-ing! :-)
