### ISSUE TITLE
custom log level 

### ISSUE THREAD

**Issue by colinyip** [ptaoussanis/timbre#139]
is there any plan to support custom levels ? something like https://logging.apache.org/log4j/2.x/manual/customloglevels.html

**Comment by ptaoussanis** [comment]
Hi Colin, no current plans but would be easy enough to add. Could you describe a use case where this would be useful?

**Comment by colinyip** [comment]
We have an appender to deal with messages with different log levels, for example, report level logs will be push to the report pipeline with some special format conversion. Now i got another type of logs similar to report logs but require different format conversion. It would be good to use the value of the same field  (log level ) to identify different type of messages in this case :) I might not be a very common case though. 

Thanks for the quick reply.

**Comment by ptaoussanis** [comment]
No problem :-)

> We have an appender to deal with messages with different log levels, 

Two quick points I'd make about this:
1. Just checking that you know you can already do this, you just need to stick to the built-in levels.
2. I'm not sure I'd recommend the approach you have in mind (as I understand it).

On [2], specifically:
Log levels as they're currently implemented are designed to control which logging calls are relevant to the current dynamic logging level. I.e. the log level is a way to filter logging calls by current level.

As I understand it, what you're looking for is a way to filter logging calls by some other concept (e.g. desired destination appender).

Now you **could** tie the desired destination appender to the log call levels, but you'd be complecting what are inherently two separate concepts. That might work okay in your particular case currently, but change in future - then you're stuck with these two concepts being tied together.

As an alternative, what if you defined an application-appropriate custom notion of `:appender-type` (or something; you'd want to name this in a way that's conceptually in line with your goals). Timbre provides all raw logging arguments to appenders, so you could easily set up a convention where, say, if the first logging argument is a special keyword - then let the appender control whether or not to dispatch.

E.g.:
```clojure

(def my-special-log-types #{:foo-type :bar-type})

(timbre/swap-config!
  (fn [m]
    (assoc m :middleware
      [(fn [data]
         (let [{:keys [vargs_]} data
               vargs @vargs_
               [varg1] vargs
               ?special-log-type (my-special-log-types varg1)
               new-vargs_
               (delay
                 (filterv (complement my-special-log-types)
                   vargs))]
           (merge data
             {:vargs_ new-vargs_ ; With special-log-type removed
              :?special-log-type ?special-log-type})))])))

(infof "Hello %s" "Steve") ; Normal info-level log call
(infof :foo-type "Hello %s" "Steve") ; info-level log call with a special-log-type
```

Then your appenders can check for the `:?special-log-type` key and act accordingly. This way you'd get the control you want, but you get it without complecting your control type and log level.

I'd note: something like this wouldn't work with Java since it'd be too difficult/clumsy to implement. So the custom log level thing is arguably the best they can do there.

Does that all help / make sense?

**Comment by colinyip** [comment]
Make sense and agree. Thanks for the great answer :)
