### ISSUE TITLE
Update 4.2.0-SNAPSHOT on Clojars

### ISSUE THREAD

**Issue by ricardojmendez** [ptaoussanis/timbre#144]
Hey Peter,

Could you please update the 4.2.0-SNAPSHOT version that it's on Clojars? The current one is using encore 2.29.0,  and the latest Faraday requires 2.29.1 at least.

Workaround: one can always exclude the `encore` from the `timbre` dependency.

**Comment by ptaoussanis** [comment]
Hi Ricardo,

This shouldn't be a problem- there'll often be different version dependencies, keeping them constantly synchronized isn't feasible or necessary.

Please see [here](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md) for some strategies for dealing with this.

You can do an exclusion, pull in an explicit encore dependency (the newer), or just put Faraday above Timbre in your dependencies.

Hope that helps?

**Comment by ricardojmendez** [comment]
Yeah, I'm excluding it myself, but haven't done enough testing yet to determine if anything broke. Thought I'd file an issue in case anyone's trying the latest Faraday alpha and ran into it.

**Comment by ptaoussanis** [comment]
> haven't done enough testing yet to determine if anything broke.

Anything broke? You mean from the encore dependency bump? Barring an unexpected bug, that should never be the case (or something that you need to test for)- encore changes are very, very rarely breaking and when they are, I make sure to update all the consumers first and cut tagged releases.

Basically isn't something you should need to be concerned about. Only time the encore deps can be a problem is if you've somehow got an insufficient version due to a dependency conflict but in that case you'll see a clear error message telling you exactly that.

**Comment by ptaoussanis** [comment]
Cutting a pair of new releases now
