### ISSUE TITLE
Validate config map?

### ISSUE THREAD

**Issue by andreasthoelke** [ptaoussanis/timbre#164]
Timbre's config approach allows to set the config map to an invalid state. E.g. doing

```clojure
(timbre/swap-config! assoc-in [:appenders :spit :enabled?] true)
```

without actually creating the spit appender before, will give you a 
`CompilerException java.lang.NullPointerException` on any log event, e.g. `(debug "test")`.

I'm not sure if it's worth setting up a schema validation of the config map. Perhaps we could simply throw a descriptive error if the appender fn isn't found?

**Comment by ptaoussanis** [comment]
Hi Andreas,

Is this just a hypothetical example, or have you actually seen this happen often? The config map has a fair number of possible options, so there's a lot of validation that _could_ be done. Unless we have a reason to suspect that certain problems are particularly common, it can sometimes create more confusion to validate certain things and not others.

Since the config's just a standard Clojure map, it's easy to inspect, modify, etc. My inclination would be to encourage folks to get into the habit of just looking at their config map instead of trying to lean on some kind of auto validation (which'd likely be imperfect).

Again, different story if there's any particular common error/s that you see a lot of people making?

Appreciate the input btw, please feel free to keep it coming!

**Comment by andreasthoelke** [comment]
Thank you for the explanation! 
Agree, it's probably better to stay simplistic. I haven't had similar problems so far.

**Comment by ptaoussanis** [comment]
No problem, thanks for floating the idea. Feel free to ping me again later if you do end up encountering any common problems later.

Cheers :-)
