### ISSUE TITLE
Rate limiting 

### ISSUE THREAD

**Issue by prayerslayer** [ptaoussanis/timbre#193]
Hi,

so I saw there's a `rate-limit` option you can give to appenders, which sounds very cool. But what happens when the rate limit is hit? Suppose I have two appenders `foo` and `bar` with rate limits 1/sec and 1/min, respectively. As far as I understood the source code, once my logs exceed a rate of 1/min, they won't be appended to `bar` anymore. This happens silently and I have no way to recover those, save for another appender without rate limits.

Are there plans to implement some queueing for logs so that they can be appended later?

Thanks!

**Comment by ptaoussanis** [comment]
Hi there!

> But what happens when the rate limit is hit? Suppose I have two appenders foo and bar with rate limits 1/sec and 1/min, respectively. As far as I understood the source code, once my logs exceed a rate of 1/min, they won't be appended to bar anymore. This happens silently and I have no way to recover those, save for another appender without rate limits.

That's correct!

> Are there plans to implement some queueing for logs so that they can be appended later?

No plans, sorry; I'd consider queuing to be separate from rate limiting. If you're looking for a queue, you can dispatch via an agent using the :async? option. Or if you're looking for a queue that pauses by rate limit/s, then that's something you'd need to define yourself (using agents again, for example).

That'd get complicated (and case-specific) way too quickly to be of general use. You'll want to clearly be able to define what happens when the queue backs up, what kind of buffering to use, etc.

Hope that helps, cheers! :-)
