### ISSUE TITLE
may-log? may returns nil with ns-whitelist

### ISSUE THREAD

**Issue by mikekap** [ptaoussanis/timbre#206]
When `ns-whitelist` is set, calls like `(may-log? :info)` returns `nil` even though it should be boolean-only. This currently causes slf4j-timbre to freak out.

**Comment by ptaoussanis** [comment]
Hi Mike, much thanks for the report! Apologies about the long delay in replying.

Will fix.

But for posterity would suggest that this ideally be something adjusted on `slf4j-timbre`'s end since in Clojure `nil` and `false` are equivalently falsey. In cases where `nil` needs to be distinguished from `false` (for example in cases of Java interop), the particular consumer should normally consider a cast (`boolean` call), or similar - to ensure that their specific requirements (e.g. interop) are met. In particular: `may-log?`'s doc-string doesn't specifically guarantee a _boolean_ output; it's name just suggests a _truthy_ output.

Cheers! :-)

**Comment by rufoa** [comment]
@ptaoussanis I've just fixed this at our end (only just seen this issue, sorry!) so feel free to revert the changes introduced in https://github.com/ptaoussanis/timbre/commit/b673a5b7875ee5cf43603b5cae4cfbb2249be93f which are no longer required
