### ISSUE TITLE
high resolution time

### ISSUE THREAD

**Issue by dsapala** [ptaoussanis/timbre#226]
What do you think about putting in high resolution time to encore and timbre? I'd like to do the work on this and use joda time if available and the java version is 7 or lower OR use the new java.time package in java 8 or above. What do you think about that?

**Comment by ptaoussanis** [comment]
Hi Dan,

What specifically do you mean by "high resolution time"? Would [nanoTime](https://github.com/ptaoussanis/encore/blob/c03938239f50cb1baa5ff2770b952fb93e358ef6/src/taoensso/encore.cljx#L1612) possibly fit the bill?

**Comment by dsapala** [comment]
Hey Peter!

I need sub-second time for our log ordering in our log aggregation platform, but the SimpleDateFormat doesn't have the capability to do higher resolution than milliseconds. I'm not sure how the nanoTime function would work with the formatting expression. Thoughts?

**Comment by ptaoussanis** [comment]
Ahh, gotcha.

To clarify: you need formatted timestamps of sub-second or _sub-millisecond_ resolution?

**Comment by dsapala** [comment]
Sub-millisecond resolution, yes. Nanoseconds would be great!

**Comment by ptaoussanis** [comment]
Hmm, that could be a tough one. I'm not sure what's available, would need to Google- but it wouldn't surprise me to hear that accurate sub-millisecond resolution timing might be tough (esp. across threads) on the JVM.

From what I can recall, even millisecond-level timing tends to be inaccurate.

Could you explain a little more about why precisely you want nanosecond-level timestamps? That seems pretty extreme. Not even sure if normal hardware can even track time to that degree of accuracy.

Note:
> public static long nanoTime()
Returns the current value of the most precise available system timer, in nanoseconds.
This method can only be used to measure elapsed time and is not related to any other notion of system or wall-clock time. The value returned represents nanoseconds since some fixed but arbitrary time (perhaps in the future, so values may be negative). This method provides nanosecond precision, but not necessarily nanosecond accuracy. No guarantees are made about how frequently values change. Differences in successive calls that span greater than approximately 292 years (263 nanoseconds) will not accurately compute elapsed time due to numerical overflow.

Ref. http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/System.html#nanoTime()

If you're just looking for for a way to strictly order log entries, perhaps an AtomicLong index would work that you increment for each logging call? That's going to involve potential contention and (I believe?) CAS underneath though, so you're still not getting strict chronological ordering exactly.

Would consider questioning whatever's leading you to think you need sub-millisecond timestamps for log entries :-)

**Comment by dsapala** [comment]
I really appreciate the thorough attention to this. Let me think about what
you've said, and I'll reply back tomorrow. Thank you!

**Comment by dsapala** [comment]
Peter, I've thought about what you said and I'm going to add the nanoTime into my output function as an "index". Thanks so much for the help!
