### ISSUE TITLE
Default appender doesn't use :?err, is this intentional?

### ISSUE THREAD

**Issue by JayAndCatchFire** [ptaoussanis/timbre#235]
The default appender for Clojure doesn't seem to respect :?err.  Is this intentional?  (Sort of related to https://github.com/ptaoussanis/timbre/pull/216)

For example, if I run
```clojure
(require '[taoensso.timbre :as log])
(log/log :debug nil "Hello!")
```
where the `nil` is in place of an exception that might be `nil`, it prints
```
17-06-30 17:24:32 computer-name DEBUG [example.core:1] - nil Hello!
```
with that superfluous `nil` there.

**Comment by JayAndCatchFire** [comment]
Can any contributors or maintainers comment on this?  Without any official say, https://github.com/nberger/ring-logger-timbre/pull/6 is kind of deadlocked.

**Comment by ptaoussanis** [comment]
Hi there! Sorry for the delay replying.

So I'm afraid I might not be properly understanding the question, sorry.

> (log/log :debug nil "Hello!") where the nil is in place of an exception that might be nil, it prints with that superfluous nil there.

You're calling `log` with an explicit nil argument- implying that you want the nil logged. If I understand correctly (?), then this doesn't have anything to do with appenders or #216.

Timbre's `log` API is as follows:

  - If the first argument is a Throwable, it's treated specially (and attached as `:?err` to the logging args).
  - Otherwise all args are treated normally.

The conditional introduced [here](https://github.com/nberger/ring-logger-timbre/pull/6/files#diff-c278bb6dd0d25644f2a261659c180c7bR11) looks perfect to me.

Or if I'm misunderstanding, maybe you could help clarify what exactly you're trying to achieve?

Cheers :-)

**Comment by JayAndCatchFire** [comment]
Your comment adds the clarity to the intent of the function signature that I was hoping for.

In the [ring-timbre-logger code](https://github.com/nberger/ring-logger-timbre/commit/05574e1d5aed904d81d0227d67f8e06123f2e57f), there was no test to see if `throwable` was `nil` before it was passed into the `log` function.  Because of that, `nil`s were being logged in almost every message.

As you can see in the discussion of https://github.com/nberger/ring-logger-timbre/pull/6#issuecomment-313039543, there was some confusion about what the intended behavior of `log` was supposed to be in regard to `nil`  being passed instead of a legitimate throwable.  Was it supposed to add it to the log message or just ignore it?  You've clarified the intent in your response.  Thank you.

**Comment by ptaoussanis** [comment]
Great, happy I could help - thanks for the follow-up 👍
