### ISSUE TITLE
two independent timbre in one project

### ISSUE THREAD

**Issue by kwladyka** [ptaoussanis/timbre#242]
I use timbre for technical log purpose. But in one project i use it for business log purpose. It is very well designed for that too! Like sending warning when price for product is probably too low, information about warehouse started to be synchronise and more serious events needed immediately attention etc.

But then there is a problem. I can't use timbre in the same project for developers and business, because of `merge-config!`.

It forces me to write almost the same only to separate logic.

Is it possible to use timbre in one project but with separated appenders?

Yeah i know it is crazy idea and probably i should use different tool just because of purpose of timbre. Eventually maybe there is something what would better fit in my needs, but i don't know this library.

**Comment by ptaoussanis** [comment]
Hi Krzysztof,

Sure, this is possible. Timbre supports a global config since that's quite convenient and covers the majority of use cases, but there's two other ways to provide config:

  1. `with-config` for thread (or expression) level config.
  2. `log*` and `logf*` which both take an explicit `config` argument.

Both/either should be applicable to your use case, you can use whichever you prefer.

Hope that helps! Cheers :-)
