### ISSUE TITLE
global-level middleware is invoked after appenders black(white)listing

### ISSUE THREAD

**Issue by ai212983** [ptaoussanis/timbre#245]
My usecase: I got a global-level `override-ns` middleware, which is changing `:?ns-str` to a new  value, redirecting message to specific appender, which is using `:ns-whitelist` for that namespace. New namespace is displayed in message, but have no effect for whitelisting. Whitelisting is done by old `:?ns-str` value. 

I believe this is a bug, because documentation clearly says that data map is being passed to appenders after being processed by global-level middleware.

**Comment by ai212983** [comment]
The only way to separate logs for different appenders with custom logic is to use now-deprecated `:middleware-fn` in appender map.

**Comment by ptaoussanis** [comment]
Hi Dimitri, this is currently expected behaviour since ns filtering is done before middleware are applied.

The order (ns filtering, then other stuff like middleware) is important for two reasons:

  1. ns filtering is an important tool for protecting performance (middleware, etc. can be expensive).
  2. ns filtering can happen at compile-time (to support logging elision).

> My usecase: I got a global-level override-ns middleware, which is changing :?ns-str to a new value, redirecting message to specific appender, which is using :ns-whitelist for that namespace. 

My 2c: even if the ns filter would still apply, this sounds like an anti-pattern to me. The namespace of a callsite is a real, immutable fact. Not sure what your objectives are exactly, but might encourage you to consider adding other relevant state to the flow of appender args rather than overwriting state with pre-existing meaning and semantics (ns in this case).

Hope that helps?

Cheers :-)
