### ISSUE TITLE
Rate limiting ignored

### ISSUE THREAD

**Issue by deepxg** [ptaoussanis/timbre#258]
I have an appender that sends stuff to Slack, and I had _hoped_ that I'd rate limited it properly, but it occasionally goes bonkers. Is there any obvious issue with this config?

```
.
.
.
:appenders {
                    :slack
                    {:enabled? true
                     :async? false
                     :min-level :warn
                     :rate-limit [[1 1000]]
                     :output-fn :inherit}
.
.
.
```

I'd assumed that meant it'd send no more than 1 message a second, but that's not the case.

**Comment by ptaoussanis** [comment]
Hi there :-)

Your config looks okay in principle.

Could you please provide some context? E.g. what you mean by "goes bonkers", if this only happens with Slack, if you have any reproducible example, etc.

**Comment by deepxg** [comment]
I think my issue here was I was expecting rate limiting to occur at the appender level (i.e. stop flooding our Slack channel), but instead it's at the error source level. So it was working, just wasn't really doing what I expected.

**Comment by boechat107** [comment]
@deepxg, I think I had the same doubt about the rate limit configuration. After reading the source code and executing some tests, I concluded the rate limit is message-dependent.

We need to think of the rate limit for each possible logging message. If all logging messages are different, no rate limit kicks in.

Is my observation correct, @ptaoussanis?

**Comment by boechat107** [comment]
The first time I tried to test the rate limit my logging messages had the value of a counter, and no limit was ever imposed. I saw the limits kicking in when I logged only two different messages in a loop.

**Comment by ptaoussanis** [comment]
Hi there! Timbre uses [this](https://github.com/ptaoussanis/timbre/blob/7bb3d648e1a49cf835233785fe2c07e43b2395da/src/taoensso/timbre.cljc#L594) heuristic for identifying logging calls for the purposes of rate-limiting, etc.

I.e. each unique _combination_ of the following identifies an individual rate-limiter:

1. Each individual Timbre macro form (e.g. `(timbre/infof ...)`).
2. When applicable, the particular message format string (only applicable for format-style logging, otherwise nil).
3. An optional manually-provided hash argument (an advanced + currently undocumented feature).

Basically: if you're using Timbre in the common way (by using macro calls like `timbre/info`, `timbre/error`, etc.) - each individual macro form will have its own limiter.

I.e. you can think of the default limiter behaviour as per logging callsite.

If you'd prefer alternative behaviour, you can either:

- Provide the optional manual hash argument in (3) above, though this currently only allows you to increase (not decrease) the set of individually identified calls. Ping if you'd like more info on this.
- Or use your own rate limiter - manually or via middleware. Timbre just uses `taoensso.encore/limiter` under-the-covers. This is a high performance and very flexible general-use rate limiter.

Hope that helps! Cheers :-)

**Comment by boechat107** [comment]
Thanks for the quick response, @ptaoussanis!

My tests confirm everything you said. I was able to find the hash composition [here](https://github.com/ptaoussanis/timbre/blob/master/src/taoensso/timbre.cljc#L594) after your comment.

Wouldn't be worth it to add a link to your comment in `*config*` docstring?

**Comment by ptaoussanis** [comment]
Will add some documentation on the next release 👍

**Comment by ptaoussanis** [comment]
Link to above comment will be added to docstring in forthcoming release, thanks Andre!
