### ISSUE TITLE
Postal appender - pleasant usage

### ISSUE THREAD

**Issue by LukasRychtecky** [ptaoussanis/timbre#259]
Hi,

when using Postal configuration and any misconfiguration is placed (e.g. wrong username, port, ...) a developer sees nothing. It would be great to notice (e.g. print out) if an e-mail has not been sent.

What do you think about it?
Thanks

**Comment by ptaoussanis** [comment]
Hi Lukáš,

Thing is- if the email appender did this out the box, we'd need/want it to be configurable. (What kinds of errors/misconfigurations do we want to catch or report? Do we print, or use an appender? At what level? Etc.).

The options end up quickly and subjectively growing.

As an alternative, I'd be inclined to suggest to folks that an appender is just a (small) fn. If you want something like this (and it's a totally reasonable thing to want!), don't feel afraid to look at how the default appender is implemented - and just implement your own version as a function that precisely fits your particular situation/preferences.

Does that make sense? Otherwise open to counter-arguments :-)

**Comment by LukasRychtecky** [comment]
Thanks for replying.

My point is I missed to place `^` for Postal configuration as meta data and I spent more an hour to figure it out where the mistake was. I think it would be enough now just print out a result of calling `send-message` when `error` is not `:SUCCESS` and the configuration.

Sure I can implement it and put it onto Github as my library. But I think it's better to save a time for others.
